### ISSUE TITLE
Invite Users to Event

### ISSUE THREAD

**Issue by jpdean123** [jpdean123/virtualrelay#25]
Need to think about process flow for this... first pass brainstorm:

1. Event admin creates the event and adds in the email address of friends they want to join
2. after event payment / submission, server sends an email out to each person. this should also create a new event in the usersEvents directory... how to store invited users? email as key? create a user then later assign them when they sign up? hmmmmmm...
3. email includes a link something like xxx.com/#/invite?eventID={{id}}
4. redirect to login page because not a user yet, add ?redirect=invite?eventID={{id}}
5. In the dashboard, show the event as "invite pending" with a button to join.
6. The join button adds them to the event

probably also want to show the invite link to the admin user so they can email / text / etc their friends directly... its hard to remember everyone's email in an external app.

**Comment by davfink** [comment]
Took a little more granular view...

1. User logs into website
2. User goes to "Create Event" page
3. User creates event
4. User is identified and assigned as event admin
5. User adds event required information (e.g. event title)
	- I say required information because there are fields like description, start/end destination that do not need to be filled out prior to creation of event
6. User is notified of event restrictions (e.g. event duration, event length, # of users)
7. User adds in the email address of friends they want to join
8. User adds in payment information
9. User submits event 
10. If errors, User is notified of all generated errors and required to fix and re-submit
11. Unique event id and link is created
 	- Is it important to differentiate between a private and sharable event link?
12. Unique sharable event link is added to event dashboard
13. After payment information is approved, server sends email out to each email address added to event
 	- this should also create a new event in the usersEvents directory... how to store invited users? email as key? create a user then later assign them when they sign up? hmmmmmm…
	- email includes basic event information (title, admin, sharable link) and a link to event (something like xxx.com/#/invite?eventID={{id}})
          DF Comment: I like using email as the key, I feel like it will make assigning users easier
14. Invited users receive email in their inbox
15. Invited user opens email and selects event link 
16. Invited user is redirected to login page
17. If not user, creates profile/signs in and continues to user home dashboard - event section
 	-  because not a user yet, add ?redirect=invite?eventID={{id}}
18. If user, invited user logs in and continues to user home dashboard - event section
19. In user dashboard - event section, event displays status as "invite pending" with a button to join.
20. User selects the join button 
21. User is added to the event
22. User strava data begins to display in event dashboard
23. User can view event dashboard
