### ISSUE TITLE
Trash Talking Enablement

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#4]
Add a chat room or comment section where i can trash talk other team mates (or congratulate them or w/e)

**Comment by jpdean123** [comment]
One thing to look at is how to notify users of new chat msgs. 

For example, we could send Everyone a new email from the same email address that contains the new messages (or msgs of the last 10 minutes).

Then, take replies from that email create new chat msgs in the chatbox.

For now, there are no notifications.. just listed on the page.

**Comment by davfink** [comment]
I dont want to be bombarding users with emails so how about something along the lines of an an end of day email that states "there were new messages in the chat room", provides link to chat page, then lists the 10 most recent messages. 

how complicated is the "replies from the email to create.." feature to set up?

**Comment by davfink** [comment]
Minor - when i got onto the page the trash talk section starts at the top and to see the latest message i'm required to scroll down. fine for now since volume is low however this will get tough once volume grows

**Comment by jpdean123** [comment]
This should be working now @davfink 

It should default to the bottom of the chat list (it does for me).

The feature to take email replies and add them to a chat isnt THAAAT complex. But I think it would take a lot of error handling since you'll have to read the email body and determine what is a reply and what is not (like an email signature, previous email listed in the body of the new email, etc.)

For now, maybe just a link to the page?

**Comment by davfink** [comment]
Default to the bottom works for me - great job!

regarding replies - link to the page sounds like a solid solution. i think that specifically taking email replies and turning them into chat messages is a low priority feature.
